config/routes.rb
Rails.application.routes.draw do
  resources :flats
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    @flats = Flat.all
  end

  # Show one
  def show
  end

  # Add a flat
  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save
    redirect_to flat_path(@flat)
  end

  # Update a flat
  def edit
  end

  def update
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  # Delete a flat
  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end

  def set_flat
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= form_for(@flat) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :price_per_night %>
    <%= f.text_field :price_per_night, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :number_of_guests %>
    <%= f.text_field :number_of_guests, class: 'form-control' %>
  </div>


  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/flats/_header.html.erb
<div class="header">
  <h2> <%= link_to "Simple Airbnb", flats_path %> </h2>
  <button> <%= link_to "Add flat", new_flat_path %> </button>
</div>

app/views/flats/edit.html.erb
<%= render 'header', flat: @flat %>
<%= render 'form', flat: @flat %>

app/views/flats/index.html.erb
<%= render 'header', flat: @flat %>

<h1>All our Flats</h1>

<div class="container">
  <% @flats.each do |flat| %>
    <div class="card">
      <div class="summary">
        <h2> <%= flat.name %> </h2>
        <p> <%= flat.address %> </p>
        <p> hosts: <%= flat.number_of_guests %> </p>
        <p> price per night: <%= flat.price_per_night %> </p>
      </div>
      <div class="links">
        <p> <%= link_to "More info", flat_path(flat) %> </p>
        <p> <%= link_to "Edit", edit_flat_path(flat) %> </p>
        <p> <%= link_to "Remove", flat_path(flat),
            method: :delete,
            data: { confirm: "Are you sure?" } %> </p>
      </div>
    </div>
  <% end %>
</div>

app/views/flats/new.html.erb
<%= render 'header', flat: @flat %>

<%= render 'form', flat: @flat %>

app/views/flats/show.html.erb
<%= render 'header', flat: @flat %>

<div class="boxes name_address col-xs-12 col-sm-4 col-lg-6">
  <h1> <%= @flat.name %> </h1>
  <p> <%= @flat.address %> </p>
</div>

<div class="boxes booking">
  <h3>Book this place</h3>
  <form action=""></form>
    <label for="From">From:</label>
    <input type="text" class="form-control" id="From" placeholder="12/10/2017">
    <label for="To">To:</label>
    <input type="text" class="form-control" id="To" placeholder="18/10/2017">
    <input type="submit" value="Book" class="btn btn-primary">
  </form>
</div>

<div class="boxes a bit more">
  <h2> A bit more about this flat </h2>
  <p><%= @flat.description %></p>
</div>

<div class="boxes details">
  <h2> Details </h2>
  <p> hosts: <%= @flat.number_of_guests %> </p>
  <p> price per night: <%= @flat.price_per_night %> </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>